### ISSUE TITLE
List of supported operations for random variables

### ISSUE THREAD

**Issue by xidulu** [justindomke/pangolin#1]
It would be great if a guide is provided on how operators support for random variables. Or more in general, how can we perform operation on random variables, e.g. softmax/sigmoid

**Comment by justindomke** [comment]
(Sorry for the long delay on this!) I'm still in the process of adding more distributions / operations. To keep things up to date, I added a handy function `interface.list_all_cond_dists()` which automatically prints out all the cond dists, organized into if they are random / not random / Classes of cond dists.

```
>>> interface.list_all_cond_dists()
List of all CondDist OBJECTS with random=True:
  normal_scale
  normal_prec
  bernoulli
  bernoulli_logit
  binomial
  uniform
  beta
  exponential
  beta_binomial
  multi_normal_cov
  categorical
  dirichlet
  multinomial
List of all CondDist OBJECTS with random=False:
  add
  sub
  mul
  div
  pow
  abs
  exp
  matmul
List of all CondDist CLASSES:
  CondDist
  Constant
  AllScalarCondDist
  VecMatCondDist
  MatMul
  Categorical
  Dirichlet
  Multinomial
  Sum
  Index
  LogProb
  VMapDist
  AbstractCondDist
```

This isn't perfect as several of the CondDist classes aren't intended to be used by end users (e.g. `AllScalarCondDist`), but at least it's guaranteed to stay up to date!

BTW please let me know if there are any particular transformations you'd like to have added as a priority. It's fairly easy to add more, just a little tedious, so I haven't made it a priority yet.
