### ISSUE TITLE
exp does not work for vmapped distribution

### ISSUE THREAD

**Issue by xidulu** [justindomke/pangolin#3]
<img width="1054" alt="Screenshot 2023-11-17 at 14 10 33" src="https://github.com/justindomke/pangolin/assets/26022201/e5c96741-35ff-45a5-8014-cdb1605807bc">

**Comment by justindomke** [comment]
This is "as intended" currently — scalar functions like exp() expect scalar arguments. If you want to do this you should use

`exp2 = vmap(x)`


`exp2(x)`

or maybe

`exp3 = vmap(vmap(X))`

Of course, it's open to debate if this is the right choice. But changing it requires some tricky choices— does `exp(X)` just *become* `vmap(X)`? Or can `exp` have arbitrary arguments. For now, I'd rather just be picky and force the user to be very explicit about vectorization, but I think other PPLs have pushed implicit vectorization a bit too far.
