### ISSUE TITLE
Clarify Python version

### ISSUE THREAD

**Issue by xidulu** [justindomke/pangolin#5]
It would be great if the required Python version (which I believe is 3.11?) can be shown in the readme.md or be enforced in setup.py

```
setup(name="my_package_name",
      python_requires='>3.11',
      [...]
```

**Comment by justindomke** [comment]
Great suggestion, thanks, done! I can confirm that python 3.10 is not currently adequate, but AFAIK 3.11 is only currently needed for a weird edge case (essentially just for `typing.Self` to create the docstring for loops.Loop!) So if there's any significant motivation to work with 3.10, please let me know, that shouldn't be hard to address.
